language: node_js
node_js:
  - "6"
services:
  - mysql
before_install:
  - echo "USE mysql;\nUPDATE user SET password=PASSWORD('pass') WHERE user='root';\nFLUSH PRIVILEGES;\n" | mysql -u root
  - mysql -e 'CREATE DATABASE IF NOT EXISTS PHARMACY;'
  - echo $DB_PASS"\n" | mysql -u root -p PHARMACY < db.sql
