language: node_js
node_js:
  - "6"
  - "7"
services:
  - mysql
before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS PHARMACY;'
  - mysql -u root PHARMACY < db.sql
  - echo "USE mysql;\nUPDATE user SET password=PASSWORD('pass') WHERE user='root';\nFLUSH PRIVILEGES;\n" | mysql -u root
