version: '2'
services:
  db:
    image: mysql:latest
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: roop
      MYSQL_DATABASE: PHARMACY
    restart: always
    volumes:
      - .:/docker-entrypoint-initdb.d
  server:
    build: .
    container_name: server
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - db
    environment:
      APP_PORT: 3000
      DB_HOST: db
      DB_USER: root
      DB_PASS: roop
      DB_DATABASE: PHARMACY
